// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsQOkWLj1vMxN8tlTo2agOh1gqZJkZt_U',
    appId: '1:452413790445:web:e8e8f2a9e86b79e41414e4',
    messagingSenderId: '452413790445',
    projectId: 'hackathon-5fccc',
    authDomain: 'hackathon-5fccc.firebaseapp.com',
    storageBucket: 'hackathon-5fccc.appspot.com',
    measurementId: 'G-51CC7DRXQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUqMz9F4b6aCJ6g68LentAJptZS19geU',
    appId: '1:452413790445:android:177d88e4d74616811414e4',
    messagingSenderId: '452413790445',
    projectId: 'hackathon-5fccc',
    storageBucket: 'hackathon-5fccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqVWqvAjMjT7CxNDHnbe_-7YUmCQv4Xok',
    appId: '1:452413790445:ios:f983bd08b8d2b58d1414e4',
    messagingSenderId: '452413790445',
    projectId: 'hackathon-5fccc',
    storageBucket: 'hackathon-5fccc.appspot.com',
    iosClientId: '452413790445-ae3d9ldbhl04j72c6hdhrj2nf3ehgcr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqVWqvAjMjT7CxNDHnbe_-7YUmCQv4Xok',
    appId: '1:452413790445:ios:f983bd08b8d2b58d1414e4',
    messagingSenderId: '452413790445',
    projectId: 'hackathon-5fccc',
    storageBucket: 'hackathon-5fccc.appspot.com',
    iosClientId: '452413790445-ae3d9ldbhl04j72c6hdhrj2nf3ehgcr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
